# Generated by Django 5.1.4 on 2026-09-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название факультета')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код / Аббревиатура')),
                ('description', models.TextField(blank=True, verbose_name='Описание факультета')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код направления подготовки')),
                ('name', models.CharField(max_length=255, verbose_name='Название направления подготовки')),
                ('education_level', models.CharField(choices=[('BACHELOR', 'Бакалавриат'), ('SPECIALIST', 'Специалитет'), ('MASTER', 'Магистратура'), ('POSTGRADUATE', 'Аспирантура'), ('COLLEGE', 'Колледж (СПОР)')], default='BACHELOR', max_length=20, verbose_name='Уровень образования')),
                ('budget_places', models.PositiveIntegerField(default=0, verbose_name='Бюджетные места')),
                ('paid_places', models.PositiveIntegerField(default=0, verbose_name='Платные места')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно для приема')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='admissions.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Направление подготовки',
                'verbose_name_plural': 'Направления подготовки',
                'ordering': ['code', 'name'],
                'unique_together': {('code', 'name', 'education_level')},
            },
        ),
    ]
