# Generated by Django 5.1.4 on 2026-09-15 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование предмета')),
                ('min_score', models.PositiveIntegerField(default=39, verbose_name='Минимальный балл')),
                ('description', models.TextField(blank=True, verbose_name='Описание / Примечания')),
            ],
            options={
                'verbose_name': 'Предмет ЕГЭ / вступительных',
                'verbose_name_plural': 'Предметы ЕГЭ / вступительных',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_form', models.CharField(choices=[('FULL_TIME', 'Очная'), ('PART_TIME', 'Заочная'), ('MIXED', 'Очно-заочная (вечерняя)')], default='FULL_TIME', max_length=20, verbose_name='Форма обучения')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость обучения в год (руб.)')),
                ('duration', models.CharField(help_text='Например: 4 года, 4 года 6 месяцев, 2 года', max_length=50, verbose_name='Срок обучения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ведется набор')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='admissions.specialty', verbose_name='Направление подготовки')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
                'ordering': ['specialty', 'study_form'],
                'unique_together': {('specialty', 'study_form')},
            },
        ),
    ]
