# Generated by Django 5.1.4 on 2026-09-15 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_examsubject_educationprogram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'Подано'), ('UNDER_REVIEW', 'На рассмотрении'), ('DOCUMENTS_REQUIRED', 'Требуются документы'), ('APPROVED', 'Одобрено (допущен к конкурсу)'), ('ENROLLED', 'Зачислен'), ('REJECTED', 'Отклонено'), ('WITHDRAWN', 'Отозвано')], default='SUBMITTED', max_length=30, verbose_name='Статус заявки')),
                ('financing_type', models.CharField(choices=[('BUDGET', 'Бюджетная основа'), ('PAID', 'Платная основа (договор)')], default='BUDGET', max_length=20, verbose_name='Основа обучения')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('officer_comment', models.TextField(blank=True, verbose_name='Комментарий приемной комиссии')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Абитуриент')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.educationprogram', verbose_name='Выбранная программа')),
            ],
            options={
                'verbose_name': 'Заявление на поступление',
                'verbose_name_plural': 'Заявления на поступление',
                'ordering': ['-submission_date'],
            },
        ),
    ]
