# Generated by Django 5.1.4 on 2026-09-15 19:45

import admissions.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Скан паспорта'), ('CERTIFICATE', 'Аттестат'), ('DIPLOMA', 'Диплом'), ('PRIVILEGE', 'Документ о льготах'), ('OTHER', 'Иной документ')], max_length=30, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to=admissions.models.application_document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Разрешены только файлы форматов PDF, JPG, JPEG, PNG.')], verbose_name='Файл документа')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверен')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application', verbose_name='Заявление')),
            ],
            options={
                'verbose_name': 'Документ заявления',
                'verbose_name_plural': 'Документы заявлений',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
