# Generated by Django 5.1.4 on 2026-09-15 19:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_applicationdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Балл не может быть меньше 0.'), django.core.validators.MaxValueValidator(100, message='Балл не может превышать 100.')], verbose_name='Балл')),
                ('exam_type', models.CharField(choices=[('EGE', 'Единый государственный экзамен (ЕГЭ)'), ('INTERNAL', 'Вступительное испытание вуза'), ('OLYMPIAD', 'Олимпиада / Особое право')], default='EGE', max_length=20, verbose_name='Тип испытания')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год сдачи')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Номер свидетельства / документа')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Балл подтвержден')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='admissions.application', verbose_name='Заявление')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='admissions.examsubject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Балл вступительного испытания',
                'verbose_name_plural': 'Баллы вступительных испытаний',
                'ordering': ['subject__name'],
                'unique_together': {('application', 'subject')},
            },
        ),
    ]
