# Generated by Django 5.1.4 on 2026-09-16 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_examscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Приемная кампания 2026', max_length=200, verbose_name='Наименование кампании')),
                ('is_active', models.BooleanField(default=True, verbose_name='Прием документов открыт')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала приема')),
                ('end_date_budget_vi', models.DateField(blank=True, null=True, verbose_name='Окончание приема с ВИ (бюджет)')),
                ('end_date_budget_ege', models.DateField(blank=True, null=True, verbose_name='Окончание приема по ЕГЭ (бюджет)')),
                ('end_date_paid', models.DateField(blank=True, null=True, verbose_name='Окончание приема на платной основе')),
                ('max_applications_per_applicant', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Лимит заявлений на одного абитуриента')),
                ('max_file_size_mb', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальный размер файла (МБ)')),
                ('allow_document_updates', models.BooleanField(default=True, verbose_name='Разрешить самостоятельную дозагрузку документов')),
                ('system_announcement', models.TextField(blank=True, verbose_name='Текст системного уведомления / объявления')),
                ('show_announcement', models.BooleanField(default=False, verbose_name='Отображать объявление на страницах портала')),
                ('announcement_type', models.CharField(choices=[('INFO', 'Информационное (Синее)'), ('WARNING', 'Предупреждение (Желтое)'), ('SUCCESS', 'Успех / Важное (Зеленое)'), ('DANGER', 'Срочное / Внимание (Красное)')], default='INFO', max_length=20, verbose_name='Тип системного объявления')),
                ('auto_notify_status_change', models.BooleanField(default=True, verbose_name='Автоматическая отправка уведомлений при смене статуса')),
                ('hotline_phone', models.CharField(default='+7 (495) 500-03-03', max_length=50, verbose_name='Телефон горячей линии')),
                ('support_email', models.EmailField(default='pk@witte.ru', max_length=254, verbose_name='Email приемной комиссии')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Настройки приемной кампании',
                'verbose_name_plural': 'Настройки приемной кампании',
            },
        ),
    ]
