# Generated by Django 5.1.4 on 2026-09-15 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('snils', models.CharField(blank=True, max_length=20, verbose_name='СНИЛС')),
                ('passport_series', models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=10, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан паспорт')),
                ('passport_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('passport_department_code', models.CharField(blank=True, max_length=10, verbose_name='Код подразделения')),
                ('address', models.TextField(blank=True, verbose_name='Адрес проживания/регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль абитуриента',
                'verbose_name_plural': 'Профили абитуриентов',
            },
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('cabinet', models.CharField(blank=True, max_length=50, verbose_name='Рабочий кабинет')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль сотрудника комиссии',
                'verbose_name_plural': 'Профили сотрудников комиссии',
            },
        ),
    ]
