# Generated by Django 5.1.4 on 2026-09-16 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN', 'Вход в систему'), ('LOGOUT', 'Выход из системы'), ('LOGIN_FAILED', 'Неудачная попытка входа'), ('ROLE_CHANGE', 'Изменение роли/прав'), ('STATUS_CHANGE', 'Смена статуса заявления'), ('DOCUMENT_VERIFY', 'Верификация документов'), ('SETTINGS_CHANGE', 'Изменение параметров кампании'), ('EXPORT_DATA', 'Экспорт данных (Excel/Word)'), ('PASSWORD_CHANGE', 'Смена пароля')], default='LOGIN', max_length=50, verbose_name='Тип события')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись журнала безопасности',
                'verbose_name_plural': 'Журнал безопасности и аудита',
                'ordering': ['-created_at'],
            },
        ),
    ]
